/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_p4a_minimal_PythonService */

#ifndef _Included_org_p4a_minimal_PythonService
#define _Included_org_p4a_minimal_PythonService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_p4a_minimal_PythonService
 * Method:    nativeMain
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_p4a_minimal_PythonService_nativeServiceStart
  (JNIEnv *, jclass,
   jstring, jstring, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
